OTC-905: disabled picking past date in product form
openimis/openimis-fe-product_js pull request #33
Opened 2023-03-14 17:09 UTC by lruzicki

Ticket:
https://openimis.atlassian.net/browse/OTC-905

Changes:
- disabled picking date from the past

2023-03-15 07:47 UTC, delcroip commented
This in not a proper solution of the problem date from must be before date to, Normally an even more complex solution is implemented in the claim "visit date" picker: in that case the only check should be date from  < date to

2023-03-15 07:47 UTC, delcroip requested changes
see comment

2023-03-16 15:28 UTC, lruzicki commented
> This in not a proper solution of the problem date from must be before date to, Normally an even more complex solution is implemented in the claim "visit date" picker: in that case the only check should be date from < date to

Thanks for pointing this out. I've fixed that by adding minDate with disablePast props. On the start you cannot select the date from the past and the DateTo picker will be up to the DateFrom. If somebody revert picking first DateTo and then later date in DateFrom he will be given a hint: "Date should not be before minimal date".
Also there is check if the DateFrom is empty and "None"/"Null" which could crash the component but it won't.

2023-03-21 11:37 UTC, delcroip approved these changes

2023-03-21 11:37 UTC, merged