ONI-181: Changed canSave method to accomodate for possible 0 value.
openimis/openimis-fe-product_js pull request #67
Opened 2023-11-09 02:06 UTC by wzglinieckisoldevelo

Ticket: https://openimis.atlassian.net/browse/ONI-181

Changes:
- Added new condition to canSave check.
- Now it allows Payment Grace Period to be equal to 0.
- This change was likely introduced in the generic core component.

2023-11-09 07:52 UTC, olewandowski1 commented on src/utils.js
> +    if (!values[field] && values[field] != 0) {
Use "!==" instead of "!=".

2023-11-09 07:53 UTC, olewandowski1 requested changes
Please refer to the comment. @wzglinieckisoldevelo

2023-11-09 08:57 UTC, wzglinieckisoldevelo commented on src/utils.js
> +    if (!values[field] && values[field] != 0) {
I hate this language.

2023-11-09 08:57 UTC, olewandowski1 commented on src/utils.js
> +    if (!values[field] && values[field] != 0) {
:x:

2023-11-09 09:31 UTC, wzglinieckisoldevelo commented
This does not work anyway, after checking saved values. I do not have time to fix it right now, so turning into draft.

2023-11-14 09:39 UTC, dragos-dobre approved these changes

2023-11-14 09:40 UTC, merged